//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace ServicioBecario.Empleados {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InformacionLaboralHttpBinding", Namespace="http://InformacionLaboral")]
    public partial class InformacionLaboralHttpService :Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaInformacionLaboralOperationCompleted;
        
        private System.Threading.SendOrPostCallback sayHelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtieneInfoSistemaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InformacionLaboralHttpService() {
            this.Url = global::ServicioBecario.Properties.Settings.Default.ServicioBecario_Empleados_InformacionLaboralHttpService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaInformacionLaboralCompletedEventHandler consultaInformacionLaboralCompleted;
        
        /// <remarks/>
        public event sayHelloCompletedEventHandler sayHelloCompleted;
        
        /// <remarks/>
        public event obtieneInfoSistemaCompletedEventHandler obtieneInfoSistemaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://InformacionLaboral/consultaInformacionLaboral", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaInformacionLaboralResponse", Namespace="http://InformacionLaboral")]
        public consultaInformacionLaboralResponse consultaInformacionLaboral([System.Xml.Serialization.XmlElementAttribute("consultaInformacionLaboral", Namespace="http://InformacionLaboral")] consultaInformacionLaboral consultaInformacionLaboral1) {
            object[] results = this.Invoke("consultaInformacionLaboral", new object[] {
                        consultaInformacionLaboral1});
            return ((consultaInformacionLaboralResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultaInformacionLaboralAsync(consultaInformacionLaboral consultaInformacionLaboral1) {
            this.consultaInformacionLaboralAsync(consultaInformacionLaboral1, null);
        }
        
        /// <remarks/>
        public void consultaInformacionLaboralAsync(consultaInformacionLaboral consultaInformacionLaboral1, object userState) {
            if ((this.consultaInformacionLaboralOperationCompleted == null)) {
                this.consultaInformacionLaboralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaInformacionLaboralOperationCompleted);
            }
            this.InvokeAsync("consultaInformacionLaboral", new object[] {
                        consultaInformacionLaboral1}, this.consultaInformacionLaboralOperationCompleted, userState);
        }
        
        private void OnconsultaInformacionLaboralOperationCompleted(object arg) {
            if ((this.consultaInformacionLaboralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaInformacionLaboralCompleted(this, new consultaInformacionLaboralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://InformacionLaboral/sayHello", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sayHelloResponse", Namespace="http://InformacionLaboral")]
        public sayHelloResponse sayHello([System.Xml.Serialization.XmlElementAttribute("sayHello", Namespace="http://InformacionLaboral")] sayHello sayHello1) {
            object[] results = this.Invoke("sayHello", new object[] {
                        sayHello1});
            return ((sayHelloResponse)(results[0]));
        }
        
        /// <remarks/>
        public void sayHelloAsync(sayHello sayHello1) {
            this.sayHelloAsync(sayHello1, null);
        }
        
        /// <remarks/>
        public void sayHelloAsync(sayHello sayHello1, object userState) {
            if ((this.sayHelloOperationCompleted == null)) {
                this.sayHelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsayHelloOperationCompleted);
            }
            this.InvokeAsync("sayHello", new object[] {
                        sayHello1}, this.sayHelloOperationCompleted, userState);
        }
        
        private void OnsayHelloOperationCompleted(object arg) {
            if ((this.sayHelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sayHelloCompleted(this, new sayHelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://InformacionLaboral/obtieneInfoSistema", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("obtieneInfoSistemaResponse", Namespace="http://InformacionLaboral")]
        public obtieneInfoSistemaResponse obtieneInfoSistema([System.Xml.Serialization.XmlElementAttribute("obtieneInfoSistema", Namespace="http://InformacionLaboral")] obtieneInfoSistema obtieneInfoSistema1) {
            object[] results = this.Invoke("obtieneInfoSistema", new object[] {
                        obtieneInfoSistema1});
            return ((obtieneInfoSistemaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void obtieneInfoSistemaAsync(obtieneInfoSistema obtieneInfoSistema1) {
            this.obtieneInfoSistemaAsync(obtieneInfoSistema1, null);
        }
        
        /// <remarks/>
        public void obtieneInfoSistemaAsync(obtieneInfoSistema obtieneInfoSistema1, object userState) {
            if ((this.obtieneInfoSistemaOperationCompleted == null)) {
                this.obtieneInfoSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtieneInfoSistemaOperationCompleted);
            }
            this.InvokeAsync("obtieneInfoSistema", new object[] {
                        obtieneInfoSistema1}, this.obtieneInfoSistemaOperationCompleted, userState);
        }
        
        private void OnobtieneInfoSistemaOperationCompleted(object arg) {
            if ((this.obtieneInfoSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtieneInfoSistemaCompleted(this, new obtieneInfoSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://InformacionLaboral")]
    public partial class consultaInformacionLaboral {
        
        private string idPersonaField;
        
        private string cveSociedadField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cveSociedad {
            get {
                return this.cveSociedadField;
            }
            set {
                this.cveSociedadField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://InformacionLaboral")]
    public partial class responseObtieneInfoSistemaType {
        
        private string codResponseField;
        
        private string descResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codResponse {
            get {
                return this.codResponseField;
            }
            set {
                this.codResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descResponse {
            get {
                return this.descResponseField;
            }
            set {
                this.descResponseField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://InformacionLaboral")]
    public partial class responseSayHelloType {
        
        private string codResponseField;
        
        private string descResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codResponse {
            get {
                return this.codResponseField;
            }
            set {
                this.codResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descResponse {
            get {
                return this.descResponseField;
            }
            set {
                this.descResponseField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://InformacionLaboral")]
    public partial class InformacionLaboralType {
        
        private string nominaField;
        
        private string contratoField;
        
        private string nombreCompletoField;
        
        private string nombreField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string sociedadField;
        
        private string descSociedadField;
        
        private string divisionField;
        
        private string descDivisionField;
        
        private string subDivisionField;
        
        private string descSubDivisionField;
        
        private string funcionField;
        
        private string descFuncionField;
        
        private string unidadOrganizacionalField;
        
        private string descUnidadOrganizacionalField;
        
        private string estatusEmpleadoField;
        
        private string descEstatusEmpleadoField;
        
        private string areaPersonalField;
        
        private string descAreaPersonalField;
        
        private string grupoPersonalField;
        
        private string descGrupoPersonalField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private string correoElectronicoField;
        
        private string ubicacionField;
        
        private string descUbicacionField;
        
        private string rfcField;
        
        private string curpField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private string frecuenciaPagoField;
        
        private string recontratoField;
        
        private string tituloField;
        
        private string extensionField;
        
        private string intercampusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nomina {
            get {
                return this.nominaField;
            }
            set {
                this.nominaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sociedad {
            get {
                return this.sociedadField;
            }
            set {
                this.sociedadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descSociedad {
            get {
                return this.descSociedadField;
            }
            set {
                this.descSociedadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descDivision {
            get {
                return this.descDivisionField;
            }
            set {
                this.descDivisionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubDivision {
            get {
                return this.subDivisionField;
            }
            set {
                this.subDivisionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descSubDivision {
            get {
                return this.descSubDivisionField;
            }
            set {
                this.descSubDivisionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Funcion {
            get {
                return this.funcionField;
            }
            set {
                this.funcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descFuncion {
            get {
                return this.descFuncionField;
            }
            set {
                this.descFuncionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnidadOrganizacional {
            get {
                return this.unidadOrganizacionalField;
            }
            set {
                this.unidadOrganizacionalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descUnidadOrganizacional {
            get {
                return this.descUnidadOrganizacionalField;
            }
            set {
                this.descUnidadOrganizacionalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EstatusEmpleado {
            get {
                return this.estatusEmpleadoField;
            }
            set {
                this.estatusEmpleadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descEstatusEmpleado {
            get {
                return this.descEstatusEmpleadoField;
            }
            set {
                this.descEstatusEmpleadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AreaPersonal {
            get {
                return this.areaPersonalField;
            }
            set {
                this.areaPersonalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descAreaPersonal {
            get {
                return this.descAreaPersonalField;
            }
            set {
                this.descAreaPersonalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrupoPersonal {
            get {
                return this.grupoPersonalField;
            }
            set {
                this.grupoPersonalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descGrupoPersonal {
            get {
                return this.descGrupoPersonalField;
            }
            set {
                this.descGrupoPersonalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descUbicacion {
            get {
                return this.descUbicacionField;
            }
            set {
                this.descUbicacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string curp {
            get {
                return this.curpField;
            }
            set {
                this.curpField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frecuenciaPago {
            get {
                return this.frecuenciaPagoField;
            }
            set {
                this.frecuenciaPagoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recontrato {
            get {
                return this.recontratoField;
            }
            set {
                this.recontratoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Intercampus {
            get {
                return this.intercampusField;
            }
            set {
                this.intercampusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://InformacionLaboral")]
    public partial class responseInformacionLaboralType {
        
        private string codResponseField;
        
        private string descResponseField;
        
        private InformacionLaboralType[] informacionLaboralField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codResponse {
            get {
                return this.codResponseField;
            }
            set {
                this.codResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descResponse {
            get {
                return this.descResponseField;
            }
            set {
                this.descResponseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("InformacionLaboral", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InformacionLaboralType[] InformacionLaboral {
            get {
                return this.informacionLaboralField;
            }
            set {
                this.informacionLaboralField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://InformacionLaboral")]
    public partial class consultaInformacionLaboralResponse {
        
        private responseInformacionLaboralType responseInformacionLaboralField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public responseInformacionLaboralType responseInformacionLaboral {
            get {
                return this.responseInformacionLaboralField;
            }
            set {
                this.responseInformacionLaboralField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://InformacionLaboral")]
    public partial class sayHello {
        
        private string nameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://InformacionLaboral")]
    public partial class sayHelloResponse {
        
        private responseSayHelloType responseSayHelloField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public responseSayHelloType responseSayHello {
            get {
                return this.responseSayHelloField;
            }
            set {
                this.responseSayHelloField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://InformacionLaboral")]
    public partial class obtieneInfoSistema {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://InformacionLaboral")]
    public partial class obtieneInfoSistemaResponse {
        
        private responseObtieneInfoSistemaType responseobtieneInfoSistemaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public responseObtieneInfoSistemaType responseobtieneInfoSistema {
            get {
                return this.responseobtieneInfoSistemaField;
            }
            set {
                this.responseobtieneInfoSistemaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultaInformacionLaboralCompletedEventHandler(object sender, consultaInformacionLaboralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaInformacionLaboralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaInformacionLaboralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultaInformacionLaboralResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultaInformacionLaboralResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sayHelloCompletedEventHandler(object sender, sayHelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sayHelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sayHelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sayHelloResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sayHelloResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void obtieneInfoSistemaCompletedEventHandler(object sender, obtieneInfoSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtieneInfoSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtieneInfoSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public obtieneInfoSistemaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((obtieneInfoSistemaResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591